services:
  - type: web
    name: mlops-mlflow
    env: python
    plan: free
    buildCommand: pip install -U pip && pip install mlflow gunicorn
    startCommand: >
      gunicorn 'mlflow.server:app'
      --bind 0.0.0.0:$PORT
      --workers 1
      --threads 2
      --timeout 120
      --log-level info
    envVars:
      # Option A: ephemeral (data lost on redeploy/restart)
      - key: MLFLOW_BACKEND_STORE_URI
        value: sqlite:////tmp/mlflow.db
      - key: MLFLOW_ARTIFACT_ROOT
        value: /tmp/mlflow-artifacts

      # Option B: external persistence (recommended for Free plan)
      # - key: MLFLOW_BACKEND_STORE_URI
      #   value: postgresql://USER:PASS@HOST:PORT/DB
      # - key: MLFLOW_ARTIFACT_ROOT
      #   value: s3://your-bucket/mlflow
      # - key: AWS_ACCESS_KEY_ID
      #   value: <key>
      # - key: AWS_SECRET_ACCESS_KEY
      #   value: <secret>
      # - key: AWS_DEFAULT_REGION
      #   value: us-east-1
      # - key: MLFLOW_S3_ENDPOINT_URL
      #   value: https://<endpoint>

  - type: web
    name: mlops-streamlit
    env: python
    plan: free
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: MLFLOW_TRACKING_URI
        fromService: { type: web, name: mlops-mlflow, property: host }
